### ISSUE TITLE
Az and AzureRM conflict

### ISSUE THREAD

**Issue by Intraligator** [diecknet/Simple-Azure-VM-Start-Stop#2]
Hi. When I try to use your runbook script - runbook test returned me following:

Script started at 2023-09-21 10:31:11
Both Az and AzureRM modules were detected on this machine. Az and AzureRM modules cannot be imported in the same session or used in the same script or runbook. If you are running PowerShell in an environment you control you can use the 'Uninstall-AzureRm' cmdlet to remove all AzureRm modules from your machine. If you are running in Azure Automation, take care that none of your runbooks import both Az and AzureRM modules. More information can be found here: https://aka.ms/azps-migration-guide

I can't delete AzureRM modules from Automation Accounts Modules  - "Delete" button not active.
What can I do? Help, plz!!!!

**Comment by diecknet** [comment]
Hi @Intraligator,

I just created a new Azure Automation Account and yes, I get the same warning. But please note this is just a Warning, not an error. So the script should still be able to Start/Stop your VMs.
I haven't seen that Warning message in the past, so most likely Microsoft changed something with the default Modules or Module versions in Azure Automation.

Screenshot with a Run that throws the Warning, but still completes successfully:
![grafik](https://github.com/diecknet/Simple-Azure-VM-Start-Stop/assets/54552094/41d70b16-f770-49dc-a0ba-0dbad2c9634a)

The warning message is misleading in my opinion:

> If you are running in Azure Automation, take care that none of your runbooks import both Az and AzureRM modules.

I don't use any AzureRM modules, as far as I'm concerned. I tried to load the modules manually, but I still get that Warning message.

```ps1
Import-Module Az.Accounts,Az.Compute
```

It's possible to suppress the Warning though, by setting the `$WarningPreference` variable.

**Comment by Intraligator** [comment]
Thank you very much! Now I see.

**Comment by Intraligator** [comment]
At the end, I just import your Power shell script as 7.1 powershell version, then updated Az Modules to 8.00 version and after that NO problem and no warnings. Thank you!

**Comment by diecknet** [comment]
Cool! Then they handle the modules somewhat differently there. I only tested the script with PowerShell 5.1. Glad to hear that it works with PowerShell 7 for you. 👍
